/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallRouteImport } from './routes/call'
import { Route as CRouteImport } from './routes/_c'
import { Route as CIndexRouteImport } from './routes/_c/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as CChatIdRouteImport } from './routes/_c/chat.$id'

const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/_c',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => CRoute,
} as any)

export interface FileRoutesByFullPath {
  '/call': typeof CallRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof CIndexRoute
  '/chat/$id': typeof CChatIdRoute
}
export interface FileRoutesByTo {
  '/call': typeof CallRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof CIndexRoute
  '/chat/$id': typeof CChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_c': typeof CRouteWithChildren
  '/call': typeof CallRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_c/': typeof CIndexRoute
  '/_c/chat/$id': typeof CChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/call' | '/login' | '/signup' | '/' | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/call' | '/login' | '/signup' | '/' | '/chat/$id'
  id:
    | '__root__'
    | '/_c'
    | '/call'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_c/'
    | '/_c/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CRoute: typeof CRouteWithChildren
  CallRoute: typeof CallRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_c': {
      id: '/_c'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_c/': {
      id: '/_c/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof CRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_c/chat/$id': {
      id: '/_c/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof CRoute
    }
  }
}

interface CRouteChildren {
  CIndexRoute: typeof CIndexRoute
  CChatIdRoute: typeof CChatIdRoute
}

const CRouteChildren: CRouteChildren = {
  CIndexRoute: CIndexRoute,
  CChatIdRoute: CChatIdRoute,
}

const CRouteWithChildren = CRoute._addFileChildren(CRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CRoute: CRouteWithChildren,
  CallRoute: CallRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
