/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallRouteImport } from './routes/call'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeProfileRouteImport } from './routes/_home/profile'
import { Route as HomeCRouteImport } from './routes/_home/_c'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as HomeCIndexRouteImport } from './routes/_home/_c/index'
import { Route as HomeCChatIdRouteImport } from './routes/_home/_c/chat.$id'

const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCRoute = HomeCRouteImport.update({
  id: '/_c',
  getParentRoute: () => HomeRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCIndexRoute = HomeCIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeCRoute,
} as any)
const HomeCChatIdRoute = HomeCChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => HomeCRoute,
} as any)

export interface FileRoutesByFullPath {
  '/call': typeof CallRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof HomeProfileRoute
  '/': typeof HomeCIndexRoute
  '/chat/$id': typeof HomeCChatIdRoute
}
export interface FileRoutesByTo {
  '/call': typeof CallRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof HomeProfileRoute
  '/': typeof HomeCIndexRoute
  '/chat/$id': typeof HomeCChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/call': typeof CallRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_home/_c': typeof HomeCRouteWithChildren
  '/_home/profile': typeof HomeProfileRoute
  '/_home/_c/': typeof HomeCIndexRoute
  '/_home/_c/chat/$id': typeof HomeCChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/call' | '/login' | '/signup' | '/profile' | '/' | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/call' | '/login' | '/signup' | '/profile' | '/' | '/chat/$id'
  id:
    | '__root__'
    | '/_home'
    | '/call'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_home/_c'
    | '/_home/profile'
    | '/_home/_c/'
    | '/_home/_c/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  CallRoute: typeof CallRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/profile': {
      id: '/_home/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/_c': {
      id: '/_home/_c'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeCRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/_c/': {
      id: '/_home/_c/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeCIndexRouteImport
      parentRoute: typeof HomeCRoute
    }
    '/_home/_c/chat/$id': {
      id: '/_home/_c/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof HomeCChatIdRouteImport
      parentRoute: typeof HomeCRoute
    }
  }
}

interface HomeCRouteChildren {
  HomeCIndexRoute: typeof HomeCIndexRoute
  HomeCChatIdRoute: typeof HomeCChatIdRoute
}

const HomeCRouteChildren: HomeCRouteChildren = {
  HomeCIndexRoute: HomeCIndexRoute,
  HomeCChatIdRoute: HomeCChatIdRoute,
}

const HomeCRouteWithChildren = HomeCRoute._addFileChildren(HomeCRouteChildren)

interface HomeRouteChildren {
  HomeCRoute: typeof HomeCRouteWithChildren
  HomeProfileRoute: typeof HomeProfileRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCRoute: HomeCRouteWithChildren,
  HomeProfileRoute: HomeProfileRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  CallRoute: CallRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
